import turtle
win = turtle.Screen()
steve = turtle.Turtle()
steve.shape('turtle')
steve.color('blue')

steve.right(90)
steve.forward(90)
steve.right(180)
steve.forward(45)
steve.right(45)
steve.forward(40)
steve.right(180)
steve.forward(45)
steve.left(90)
steve.forward(45)
steve.penup()
steve.left(45)
steve.forward(30)
steve.pendown()
steve.forward(45)
steve.left(90)
steve.forward(45)
steve.left(90)
steve.forward(45)
steve.right(90)
steve.forward(45)
steve.right(90)
steve.forward(45)
